### ISSUE TITLE
在 DoorDataReceiver 中  “继续找到下一个3AA3”  这个命令是应该是头字节嘛？

### ISSUE THREAD

**Issue by zjianflys** [licheedev/SerialWorker#3]
我对ByteBuffer 用的不是很熟,
**if (dataN > Protocol.MAX_N) {
                    //回到“第二位”，继续找到下一个3AA3
                    mByteBuffer.position(frameStart + 2);
                    continue;
                }**
mByteBuffer.position(frameStart + 2)  这句代码是又去找头字节嘛  我看你协议里面头字节不是3AA3  所以有点不清楚.

**Comment by licheedev** [comment]
@zjianflys 
因为我3AA3和3BB3的协议都写过，所以copy的时候忘记把注释改全了。以具体的代码为准。
